// <auto-generated />
using System;
using HRSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HRSystemDbContext))]
    [Migration("20260727142532_AddBioWebTaAttendanceImportFoundation")]
    partial class AddBioWebTaAttendanceImportFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("EmployeeNumberSequence", "dbo")
                .StartsAt(15L)
                .HasMin(15L)
                .HasMax(9999L);

            modelBuilder.Entity("HRSystem.Domain.Attendance.AttendanceRawEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceSerialNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EventLocalDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<long>("ExternalEventId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsSourceMissing")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("SourceCreatedTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("SourcePersonPin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<int?>("VerifyCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "EventLocalDateTime")
                        .HasDatabaseName("IX_AttendanceRawEvents_EmployeeId_EventLocalDateTime");

                    b.HasIndex("SourceSystem", "ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("UX_AttendanceRawEvents_SourceSystem_ExternalEventId");

                    b.HasIndex("SourceSystem", "IsSourceMissing", "ExternalEventId")
                        .HasDatabaseName("IX_AttendanceRawEvents_SourceMissing_ExternalEventId");

                    b.HasIndex("SourceSystem", "SourcePersonPin", "EventLocalDateTime")
                        .HasDatabaseName("IX_AttendanceRawEvents_UnmappedPin_EventLocalDateTime")
                        .HasFilter("[EmployeeId] IS NULL");

                    b.ToTable("AttendanceRawEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_AttendanceRawEvents_ExternalEventId_Positive", "[ExternalEventId] > 0");
                        });
                });

            modelBuilder.Entity("HRSystem.Domain.Attendance.AttendanceSyncState", b =>
                {
                    b.Property<string>("SourceSystem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset>("LastAttemptAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastErrorSummary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("LastExternalEventId")
                        .HasColumnType("bigint");

                    b.Property<int>("LastImportedCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastSuccessfulSyncAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("SourceSystem");

                    b.ToTable("AttendanceSyncStates", null, t =>
                        {
                            t.HasCheckConstraint("CK_AttendanceSyncStates_LastExternalEventId", "[LastExternalEventId] >= 0");

                            t.HasCheckConstraint("CK_AttendanceSyncStates_LastImportedCount", "[LastImportedCount] >= 0");
                        });
                });

            modelBuilder.Entity("HRSystem.Domain.Attendance.BioWebPersonMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BioWebPin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BioWebPin", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("UX_BioWebPersonMappings_BioWebPin_EffectiveFrom");

                    b.HasIndex("EmployeeId", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("UX_BioWebPersonMappings_EmployeeId_EffectiveFrom");

                    b.HasIndex("BioWebPin", "IsActive", "EffectiveFrom", "EffectiveTo")
                        .HasDatabaseName("IX_BioWebPersonMappings_Pin_Active_Period");

                    b.HasIndex("EmployeeId", "IsActive", "EffectiveFrom", "EffectiveTo")
                        .HasDatabaseName("IX_BioWebPersonMappings_Employee_Active_Period");

                    b.ToTable("BioWebPersonMappings", null, t =>
                        {
                            t.HasCheckConstraint("CK_BioWebPersonMappings_EffectivePeriod", "[EffectiveTo] IS NULL OR [EffectiveTo] > [EffectiveFrom]");
                        });
                });

            modelBuilder.Entity("HRSystem.Domain.Auditing.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_AuditLogs_CreatedAtUtc");

                    b.HasIndex("Action", "CreatedAtUtc")
                        .HasDatabaseName("IX_AuditLogs_Action_CreatedAtUtc");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_EntityType_EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("HRSystem.Domain.CompanyCalendars.CompanyCalendarDay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("BaseDayType")
                        .HasColumnType("tinyint");

                    b.Property<string>("BaseName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CalendarYear")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyCalendarYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<byte>("DayType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CalendarYear", "Date")
                        .HasDatabaseName("IX_CompanyCalendarDays_CalendarYear_Date");

                    b.HasIndex("CompanyCalendarYearId", "CalendarYear");

                    b.HasIndex("CompanyCalendarYearId", "Date")
                        .IsUnique()
                        .HasDatabaseName("UX_CompanyCalendarDays_Year_Date");

                    b.ToTable("CompanyCalendarDays", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompanyCalendarDays_BaseDayType", "[BaseDayType] IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_CompanyCalendarDays_DateYear", "DATEPART(year, [Date]) = [CalendarYear]");

                            t.HasCheckConstraint("CK_CompanyCalendarDays_DayType", "[DayType] IN (1, 2, 3, 4, 5, 6, 7)");

                            t.HasCheckConstraint("CK_CompanyCalendarDays_NameRequired", "[DayType] IN (1, 2, 3) OR ([Name] IS NOT NULL AND LEN(LTRIM(RTRIM([Name]))) > 0)");

                            t.HasCheckConstraint("CK_CompanyCalendarDays_OverrideConsistency", "([OverrideReason] IS NULL AND [DayType] = [BaseDayType]) OR ([OverrideReason] IS NOT NULL AND LEN(LTRIM(RTRIM([OverrideReason]))) > 0)");
                        });
                });

            modelBuilder.Entity("HRSystem.Domain.CompanyCalendars.CompanyCalendarYear", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ArchivedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManifestHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ManifestVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceAuthority")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceContentHash")
                        .HasColumnType("char(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("SourceDocumentIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("SourcePublishedDate")
                        .HasColumnType("date");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SourceTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "Year")
                        .HasName("AK_CompanyCalendarYears_Id_Year");

                    b.HasIndex("Year")
                        .IsUnique()
                        .HasDatabaseName("UX_CompanyCalendarYears_Year");

                    b.HasIndex("Status", "Year")
                        .HasDatabaseName("IX_CompanyCalendarYears_Status_Year");

                    b.ToTable("CompanyCalendarYears", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompanyCalendarYears_LifecycleMetadata", "([Status] = 1 AND [PublishedAtUtc] IS NULL AND [PublishedBy] IS NULL AND [ArchivedAtUtc] IS NULL AND [ArchivedBy] IS NULL) OR ([Status] = 2 AND [PublishedAtUtc] IS NOT NULL AND [PublishedBy] IS NOT NULL AND [ArchivedAtUtc] IS NULL AND [ArchivedBy] IS NULL) OR ([Status] = 3 AND [PublishedAtUtc] IS NOT NULL AND [PublishedBy] IS NOT NULL AND [ArchivedAtUtc] IS NOT NULL AND [ArchivedBy] IS NOT NULL)");

                            t.HasCheckConstraint("CK_CompanyCalendarYears_ManifestHash", "LEN([ManifestHash]) = 64 AND [ManifestHash] NOT LIKE '%[^0-9a-f]%' COLLATE Latin1_General_100_BIN2");

                            t.HasCheckConstraint("CK_CompanyCalendarYears_SourceContentHash", "[SourceContentHash] IS NULL OR (LEN([SourceContentHash]) = 64 AND [SourceContentHash] NOT LIKE '%[^0-9a-f]%' COLLATE Latin1_General_100_BIN2)");

                            t.HasCheckConstraint("CK_CompanyCalendarYears_Status", "[Status] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_CompanyCalendarYears_Year_Range", "[Year] >= 1 AND [Year] <= 9999");
                        });
                });

            modelBuilder.Entity("HRSystem.Domain.LeaveRequests.LeaveApprovalHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Action")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset>("ActionAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ActionByDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActionByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte>("FromStatus")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("LeaveRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ToStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ActionByUserId")
                        .HasDatabaseName("IX_LeaveApprovalHistories_ActionByUserId");

                    b.HasIndex("LeaveRequestId", "ActionAtUtc")
                        .HasDatabaseName("IX_LeaveApprovalHistories_LeaveRequestId_ActionAtUtc");

                    b.ToTable("LeaveApprovalHistories", (string)null);
                });

            modelBuilder.Entity("HRSystem.Domain.LeaveRequests.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DurationHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("RejectedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("WithdrawnAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_LeaveRequests_CreatedAtUtc");

                    b.HasIndex("LeaveTypeId")
                        .HasDatabaseName("IX_LeaveRequests_LeaveTypeId");

                    b.HasIndex("RequestNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_LeaveRequests_RequestNumber");

                    b.HasIndex("Status", "SubmittedAtUtc")
                        .HasDatabaseName("IX_LeaveRequests_Status_SubmittedAtUtc");

                    b.HasIndex("EmployeeId", "StartAt", "EndAt")
                        .HasDatabaseName("IX_LeaveRequests_EmployeeId_StartAt_EndAt");

                    b.ToTable("LeaveRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaveRequests_DurationHours_Positive", "[DurationHours] > 0");

                            t.HasCheckConstraint("CK_LeaveRequests_EndAfterStart", "[EndAt] > [StartAt]");
                        });
                });

            modelBuilder.Entity("HRSystem.Domain.MasterData.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ManagerEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Departments_Code");

                    b.HasIndex("ManagerEmployeeId")
                        .HasDatabaseName("IX_Departments_ManagerEmployeeId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("HRSystem.Domain.MasterData.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChineseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly?>("TerminationDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ChineseName")
                        .HasDatabaseName("IX_Employees_ChineseName");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Employees_EmployeeNumber");

                    b.HasIndex("DepartmentId", "IsActive")
                        .HasDatabaseName("IX_Employees_DepartmentId_IsActive");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("HRSystem.Domain.MasterData.LeaveType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinimumUnit")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiresReason")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<byte>("Unit")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_LeaveTypes_Code");

                    b.HasIndex("IsActive", "SortOrder")
                        .HasDatabaseName("IX_LeaveTypes_IsActive_SortOrder");

                    b.ToTable("LeaveTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaveTypes_MinimumUnit_Positive", "[MinimumUnit] > 0");

                            t.HasCheckConstraint("CK_LeaveTypes_SortOrder_NonNegative", "[SortOrder] >= 0");
                        });
                });

            modelBuilder.Entity("HRSystem.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UX_AspNetUsers_EmployeeId")
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex")
                        .HasFilter("[NormalizedEmail] IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HRSystem.Domain.Attendance.AttendanceRawEvent", b =>
                {
                    b.HasOne("HRSystem.Domain.MasterData.Employee", "Employee")
                        .WithMany("AttendanceRawEvents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRSystem.Domain.Attendance.BioWebPersonMapping", b =>
                {
                    b.HasOne("HRSystem.Domain.MasterData.Employee", "Employee")
                        .WithMany("BioWebPersonMappings")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRSystem.Domain.CompanyCalendars.CompanyCalendarDay", b =>
                {
                    b.HasOne("HRSystem.Domain.CompanyCalendars.CompanyCalendarYear", "Year")
                        .WithMany("Days")
                        .HasForeignKey("CompanyCalendarYearId", "CalendarYear")
                        .HasPrincipalKey("Id", "Year")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Year");
                });

            modelBuilder.Entity("HRSystem.Domain.LeaveRequests.LeaveApprovalHistory", b =>
                {
                    b.HasOne("HRSystem.Domain.LeaveRequests.LeaveRequest", "LeaveRequest")
                        .WithMany("ApprovalHistories")
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeaveRequest");
                });

            modelBuilder.Entity("HRSystem.Domain.LeaveRequests.LeaveRequest", b =>
                {
                    b.HasOne("HRSystem.Domain.MasterData.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRSystem.Domain.MasterData.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("HRSystem.Domain.MasterData.Department", b =>
                {
                    b.HasOne("HRSystem.Domain.MasterData.Employee", "ManagerEmployee")
                        .WithMany("ManagedDepartments")
                        .HasForeignKey("ManagerEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ManagerEmployee");
                });

            modelBuilder.Entity("HRSystem.Domain.MasterData.Employee", b =>
                {
                    b.HasOne("HRSystem.Domain.MasterData.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HRSystem.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.HasOne("HRSystem.Domain.MasterData.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("HRSystem.Infrastructure.Identity.ApplicationUser", "EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HRSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HRSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HRSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRSystem.Domain.CompanyCalendars.CompanyCalendarYear", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("HRSystem.Domain.LeaveRequests.LeaveRequest", b =>
                {
                    b.Navigation("ApprovalHistories");
                });

            modelBuilder.Entity("HRSystem.Domain.MasterData.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HRSystem.Domain.MasterData.Employee", b =>
                {
                    b.Navigation("AttendanceRawEvents");

                    b.Navigation("BioWebPersonMappings");

                    b.Navigation("ManagedDepartments");
                });
#pragma warning restore 612, 618
        }
    }
}
